package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import structures.BinarySearchTree;

public class BinarySearchTreeViewer extends JPanel {

    private BinarySearchTree tree;
    
    /**
     * Creates new form SequentialList
     */
    public BinarySearchTreeViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLoad = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        operationsPanel = new javax.swing.JPanel();
        btCreate = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();

        btLoad.setText("Load");
        btLoad.setEnabled(false);

        btSave.setText("Save");
        btSave.setToolTipText("");
        btSave.setEnabled(false);

        operationsPanel.setPreferredSize(new java.awt.Dimension(780, 57));
        operationsPanel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btCreate.setText("New Tree");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });
        operationsPanel.add(btCreate);

        btAdd.setText("Insert");
        btAdd.setEnabled(false);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        operationsPanel.add(btAdd);

        btSearch.setText("Search");
        btSearch.setEnabled(false);
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        operationsPanel.add(btSearch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(operationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(operationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        tree = new BinarySearchTree(scrollPane);
        btSearch.setEnabled(true);
        btAdd.setEnabled(true);
        tree.showTree();
    }//GEN-LAST:event_btCreateActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        String input;
        int value = 0;
        try{
            input = JOptionPane.showInputDialog(this, Constants.PORTUGUESE ? Constants.LIST_PT[16] : "Insert the value", "Info", JOptionPane.QUESTION_MESSAGE);
            if(input == null){
                return;
            }
            value = Integer.parseInt(input);
            tree.search(value);  
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, Constants.PORTUGUESE ? Constants.ERRORS_PT[1] : "Value must be a integer!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            tree.insert(value);
            tree.showTree();
        }       
    }//GEN-LAST:event_btAddActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String input;
        int value;
        try{
            input = JOptionPane.showInputDialog(this, Constants.PORTUGUESE ? Constants.LIST_PT[16] : "Insert the value to search for", "Info", JOptionPane.QUESTION_MESSAGE);
            if(input == null){
                return;
            }
            value = Integer.parseInt(input);
            tree.search(value);
            tree.showTree(value);
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, Constants.PORTUGUESE ? Constants.ERRORS_PT[1] : "Value must be a integer!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btLoad;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSearch;
    private javax.swing.JPanel operationsPanel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
